name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - run: npm ci
      - run: npm run build
      - name: Create release package
        run: |
          cd dist
          tar -zcvf ../jira-chrome-ext-${{ github.ref_name }}.tgz .
          cd ..
      - name: Create Release
        uses: gh-actions-community/action-create-release@main
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            # Release ${{ github.ref_name }}
            
            Chrome extension package ready for installation or Chrome Web Store submission.
            
            ## Installation
            1. Download the attached .tgz file
            2. Extract to a folder
            3. Go to chrome://extensions
            4. Enable Developer mode
            5. Click "Load unpacked" and select the extracted folder
            
            ## Changes
            See commit history for detailed changes in this release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./jira-chrome-ext-${{ github.ref_name }}.tgz
          asset_name: jira-chrome-ext-${{ github.ref_name }}.tgz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

